// Python codegen backend — AST to .n2py compiled contract
use crate::ast::*;
use super::{CodeGenerator, CodegenError, CompilationMeta};

pub struct PythonBackend;

impl CodeGenerator for PythonBackend {
    fn target_name(&self) -> &str { "python" }
    fn file_extension(&self) -> &str { ".n2py" }

    fn generate(&self, ast: &N2File, meta: &CompilationMeta) -> Result<String, CodegenError> {
        let mut out = String::with_capacity(4096);

        emit_header(&mut out, meta);
        emit_prelude(&mut out);

        for block in &ast.blocks {
            match block {
                Block::Contract(ct) => emit_contract(&mut out, ct),
                Block::Rule(r) => emit_rule(&mut out, r),
                Block::Workflow(w) => emit_workflow(&mut out, w),
                _ => {}
            }
        }

        Ok(out)
    }
}

fn emit_header(out: &mut String, meta: &CompilationMeta) {
    out.push_str(&format!(
        "# N2 Compiled Contract — Python target\n\
         # Source: {}\n\
         # Version: {}\n\
         # Compiler: {}\n\
         # Compiled: {}\n\n",
        meta.source_name, meta.source_version,
        meta.compiler_version, meta.compiled_at
    ));
}

fn emit_prelude(out: &mut String) {
    out.push_str(
        "\"\"\"N2 Compiled Contract — Auto-generated by Clotho compiler.\"\"\"\n\
         from enum import Enum, auto\n\
         from typing import Optional, Tuple\n\n\n\
         class ContractViolation(Exception):\n\
         \x20   \"\"\"Raised when an invalid state transition is attempted.\"\"\"\n\
         \x20   def __init__(self, contract: str, from_state: str, event: str):\n\
         \x20       self.contract = contract\n\
         \x20       self.from_state = from_state\n\
         \x20       self.event = event\n\
         \x20       super().__init__(\n\
         \x20           f\"[{contract}] invalid transition from {from_state} on '{event}'\"\n\
         \x20       )\n\n\n"
    );
}

fn emit_contract(out: &mut String, ct: &ContractBlock) {
    if ct.transitions.is_empty() { return; }

    let name = &ct.name;
    let states = collect_states(&ct.transitions);

    // Emit enum
    out.push_str(&format!("class {}State(Enum):\n", name));
    out.push_str("    \"\"\"State machine states.\"\"\"\n");
    for s in &states {
        out.push_str(&format!("    {} = auto()\n", s));
    }
    out.push_str("\n\n");

    // Emit transitions dict
    out.push_str(&format!("_{}_TRANSITIONS = {{\n", name.to_uppercase()));
    for t in &ct.transitions {
        out.push_str(&format!(
            "    ({name}State.{from}, \"{ev}\"): {name}State.{to},\n",
            name = name, from = t.from, to = t.to, ev = t.on_event
        ));
    }
    out.push_str("}\n\n\n");

    // Emit class
    out.push_str(&format!(
        "class {}:\n\
         \x20   \"\"\"Contract state machine: {}.\"\"\"\n\n\
         \x20   def __init__(self) -> None:\n\
         \x20       self.state = {}State.{}\n\n\
         \x20   @property\n\
         \x20   def current_state(self) -> str:\n\
         \x20       return self.state.name\n\n\
         \x20   def transition(self, event: str) -> str:\n\
         \x20       key = (self.state, event)\n\
         \x20       next_state = _{}_TRANSITIONS.get(key)\n\
         \x20       if next_state is None:\n\
         \x20           raise ContractViolation(\n\
         \x20               contract=\"{}\",\n\
         \x20               from_state=self.state.name,\n\
         \x20               event=event,\n\
         \x20           )\n\
         \x20       self.state = next_state\n\
         \x20       return self.state.name\n\n\n",
        name, name, name, states[0],
        name.to_uppercase(), name
    ));
}

fn emit_rule(out: &mut String, rule: &RuleBlock) {
    if rule.blacklist.is_empty() { return; }

    let name = &rule.name;
    out.push_str(&format!(
        "class {}Rule:\n\
         \x20   \"\"\"Rule: {}.\"\"\"\n\n\
         \x20   BLACKLIST = [\n",
        name, name
    ));
    for p in &rule.blacklist {
        let clean = p.trim_matches('/').trim_end_matches('i');
        out.push_str(&format!("        \"{}\",\n", clean));
    }
    out.push_str(
        "    ]\n\n\
         \x20   @classmethod\n\
         \x20   def check_blacklist(cls, input_text: str) -> Tuple[Optional[str], bool]:\n\
         \x20       for pattern in cls.BLACKLIST:\n\
         \x20           if pattern in input_text:\n\
         \x20               return pattern, True\n\
         \x20       return None, False\n\n\n"
    );
}

fn emit_workflow(out: &mut String, wf: &WorkflowBlock) {
    let name = &wf.name;
    out.push_str(&format!(
        "class {}Workflow:\n\
         \x20   \"\"\"Workflow: {}.\"\"\"\n\n\
         \x20   STEPS = [\n",
        name, name
    ));
    for step in &wf.steps {
        out.push_str(&format!("        \"{}\",\n", step.name));
    }
    out.push_str("    ]\n\n\n");
}

fn collect_states(transitions: &[TransitionStmt]) -> Vec<String> {
    let mut seen = Vec::new();
    for t in transitions {
        if !seen.contains(&t.from) { seen.push(t.from.clone()); }
        if !seen.contains(&t.to) { seen.push(t.to.clone()); }
    }
    seen
}
