// TypeScript codegen backend — AST to .n2ts compiled contract
use crate::ast::*;
use super::{CodeGenerator, CodegenError, CompilationMeta};

pub struct TypeScriptBackend;

impl CodeGenerator for TypeScriptBackend {
    fn target_name(&self) -> &str { "ts" }
    fn file_extension(&self) -> &str { ".n2ts" }

    fn generate(&self, ast: &N2File, meta: &CompilationMeta) -> Result<String, CodegenError> {
        let mut out = String::with_capacity(4096);

        emit_header(&mut out, meta);
        emit_prelude(&mut out);

        for block in &ast.blocks {
            match block {
                Block::Contract(ct) => emit_contract(&mut out, ct),
                Block::Rule(r) => emit_rule(&mut out, r),
                Block::Workflow(w) => emit_workflow(&mut out, w),
                _ => {}
            }
        }

        Ok(out)
    }
}

fn emit_header(out: &mut String, meta: &CompilationMeta) {
    out.push_str(&format!(
        "// N2 Compiled Contract — TypeScript target\n\
         // Source: {}\n\
         // Version: {}\n\
         // Compiler: {}\n\
         // Compiled: {}\n\n",
        meta.source_name, meta.source_version,
        meta.compiler_version, meta.compiled_at
    ));
}

fn emit_prelude(out: &mut String) {
    out.push_str(
        "/** N2 Compiled Contract — Auto-generated by Clotho compiler. */\n\n\
         export class ContractViolation extends Error {\n\
         \x20 constructor(\n\
         \x20   public readonly contract: string,\n\
         \x20   public readonly fromState: string,\n\
         \x20   public readonly event: string,\n\
         \x20 ) {\n\
         \x20   super(`[${contract}] invalid transition from ${fromState} on '${event}'`);\n\
         \x20   this.name = 'ContractViolation';\n\
         \x20 }\n\
         }\n\n"
    );
}

fn emit_contract(out: &mut String, ct: &ContractBlock) {
    if ct.transitions.is_empty() { return; }

    let name = &ct.name;
    let states = collect_states(&ct.transitions);

    // Emit enum
    out.push_str(&format!("/** State machine: {} */\n", name));
    out.push_str(&format!("export enum {}State {{\n", name));
    for s in &states {
        out.push_str(&format!("  {} = '{}',\n", s, s));
    }
    out.push_str("}\n\n");

    // Emit transition map
    out.push_str(&format!(
        "const {}_TRANSITIONS: Record<string, {}State> = {{\n",
        name.to_uppercase(), name
    ));
    for t in &ct.transitions {
        out.push_str(&format!(
            "  '{}:{}': {}State.{},\n",
            t.from, t.on_event, name, t.to
        ));
    }
    out.push_str("};\n\n");

    // Emit class
    out.push_str(&format!(
        "export class {} {{\n\
         \x20 private state: {name}State = {name}State.{first};\n\n\
         \x20 get currentState(): string {{\n\
         \x20   return this.state;\n\
         \x20 }}\n\n\
         \x20 transition(event: string): string {{\n\
         \x20   const key = `${{this.state}}:${{event}}`;\n\
         \x20   const next = {upper}_TRANSITIONS[key];\n\
         \x20   if (next === undefined) {{\n\
         \x20     throw new ContractViolation('{name}', this.state, event);\n\
         \x20   }}\n\
         \x20   this.state = next;\n\
         \x20   return this.state;\n\
         \x20 }}\n\
         }}\n\n",
        name, name = name, first = states[0], upper = name.to_uppercase()
    ));
}

fn emit_rule(out: &mut String, rule: &RuleBlock) {
    if rule.blacklist.is_empty() { return; }

    out.push_str(&format!("/** Rule: {} */\n", rule.name));
    out.push_str(&format!("export class {}Rule {{\n", rule.name));
    out.push_str("  private static readonly BLACKLIST: string[] = [\n");
    for p in &rule.blacklist {
        let clean = p.trim_matches('/').trim_end_matches('i');
        out.push_str(&format!("    '{}',\n", clean));
    }
    out.push_str("  ];\n\n");
    out.push_str(
        "  static checkBlacklist(input: string): string | null {\n\
         \x20   for (const pattern of this.BLACKLIST) {\n\
         \x20     if (input.includes(pattern)) return pattern;\n\
         \x20   }\n\
         \x20   return null;\n\
         \x20 }\n\
         }\n\n"
    );
}

fn emit_workflow(out: &mut String, wf: &WorkflowBlock) {
    out.push_str(&format!("/** Workflow: {} */\n", wf.name));
    out.push_str(&format!(
        "export const {}Steps: readonly string[] = [\n",
        wf.name.chars().next().unwrap().to_lowercase().collect::<String>() + &wf.name[1..]
    ));
    for step in &wf.steps {
        out.push_str(&format!("  '{}',\n", step.name));
    }
    out.push_str("] as const;\n\n");
}

fn collect_states(transitions: &[TransitionStmt]) -> Vec<String> {
    let mut seen = Vec::new();
    for t in transitions {
        if !seen.contains(&t.from) { seen.push(t.from.clone()); }
        if !seen.contains(&t.to) { seen.push(t.to.clone()); }
    }
    seen
}
